title: "SoHo Pilates Studio"
email: "concierge@sohopilates.com"
description: "Elite classical and contemporary reformer Pilates studio located in the heart of SoHo, New York."
baseurl: "/SoHo-Pilates-Studio" # Adjust to match repository name
url: "https://khisal786.github.io"

markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"